modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "perf_tweaks"
version = "${version}"
displayName = "PerformanceTweaks"
authors = ""
description = '''
A performance tweaks mod.
'''
accessTransformer = "META-INF/accesstransformer.cfg"
logoFile = "icon.png"

[[dependencies.perf_tweaks]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.perf_tweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.perf_tweaks]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[accessTransformers]]
## The file is relative to the output directory of the resources, or the root path inside the jar when compiled
## The 'resources' directory represents the root output directory of the resources
file = "META-INF/accesstransformer.cfg"