modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "perf_tweaks"
version = "${version}"
displayName = "Performance Tweaks"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.perf_tweaks]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.perf_tweaks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.perf_tweaks]]
modId = "architectury"
type = "required"
versionRange = "[14.0.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "perf_tweaks.mixins.json"
